# Generated by Django 5.2.7 on 2025-10-18 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentFormData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(choices=[('direction', 'Direction'), ('cinematography', 'Cinematography'), ('editing', 'Editing'), ('sound', 'Sound')], max_length=50)),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=15)),
                ('date_of_birth', models.DateField()),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('pin_code', models.CharField(max_length=10)),
                ('years_of_experience', models.IntegerField()),
                ('key_skills', models.TextField()),
                ('previous_projects', models.TextField(blank=True, null=True)),
                ('availability', models.CharField(max_length=50)),
                ('expected_salary_range', models.CharField(max_length=50)),
                ('performed_work_location', models.CharField(max_length=100)),
                ('educational_qualification', models.TextField()),
                ('certifications_training', models.TextField(blank=True, null=True)),
                ('awards_recognition', models.TextField(blank=True, null=True)),
                ('portfolio_website', models.URLField(blank=True, null=True)),
                ('linkedin_profile', models.URLField(blank=True, null=True)),
                ('imdb_profile', models.URLField(blank=True, null=True)),
                ('document_upload', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('additional_info', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
