# Generated by Django 5.2.7 on 2025-10-18 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cineapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(choices=[('direction', 'Direction Department'), ('editing', 'Editing Department'), ('cinematography', 'Cinematography Department')], max_length=50)),
                ('full_name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=15)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('pin_code', models.CharField(max_length=10)),
                ('years_of_experience', models.IntegerField(blank=True, null=True)),
                ('key_skills', models.TextField(blank=True)),
                ('previous_projects', models.TextField(blank=True)),
                ('availability', models.CharField(blank=True, max_length=100)),
                ('expected_salary_range', models.CharField(blank=True, max_length=100)),
                ('performed_work_location', models.CharField(blank=True, max_length=200)),
                ('educational_qualification', models.TextField(blank=True)),
                ('certifications_training', models.TextField(blank=True)),
                ('awards_recognition', models.TextField(blank=True)),
                ('portfolio_link', models.URLField(blank=True)),
                ('linkedin_profile', models.URLField(blank=True)),
                ('imdb_profile', models.URLField(blank=True)),
                ('resume_upload', models.FileField(blank=True, null=True, upload_to='uploads/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='DepartmentFormData',
        ),
    ]
