# Generated by Django 5.2.7 on 2025-10-18 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cineapp', '0002_departmentprofile_delete_departmentformdata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='departmentprofile',
            name='department',
        ),
        migrations.AddField(
            model_name='departmentprofile',
            name='department_name',
            field=models.CharField(default='temp', max_length=100),
            preserve_default=False,
        ),
    ]
