# Generated by Django 5.2.7 on 2025-10-18 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cineapp', '0003_remove_departmentprofile_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='departmentprofile',
            name='additional_information',
            field=models.TextField(blank=True, null=True),
        ),
    ]
