# Generated by Django 5.2.7 on 2025-10-18 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cineapp', '0004_departmentprofile_additional_information'),
    ]

    operations = [
        migrations.AddField(
            model_name='departmentprofile',
            name='application_id',
            field=models.CharField(blank=True, db_index=True, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='departmentprofile',
            name='guid',
            field=models.UUIDField(blank=True, editable=False, null=True),
        ),
    ]
