# Generated by Django 5.2.7 on 2025-10-19 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cineapp', '0006_departmentprofile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departmentprofile',
            name='application_id',
            field=models.CharField(blank=True, db_index=True, max_length=16, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='departmentprofile',
            name='guid',
            field=models.UUIDField(blank=True, editable=False, null=True, unique=True),
        ),
    ]
