# Generated by Django 5.2.7 on 2025-10-19 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cineapp', '0007_alter_departmentprofile_application_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='departmentprofile',
            name='approval_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=16),
        ),
    ]
