# Generated by Django 5.2.7 on 2025-10-19 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cineapp', '0008_departmentprofile_approval_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='departmentprofile',
            name='additional_information',
        ),
        migrations.RemoveField(
            model_name='departmentprofile',
            name='availability',
        ),
        migrations.RemoveField(
            model_name='departmentprofile',
            name='awards_recognition',
        ),
        migrations.RemoveField(
            model_name='departmentprofile',
            name='certifications_training',
        ),
        migrations.RemoveField(
            model_name='departmentprofile',
            name='educational_qualification',
        ),
        migrations.RemoveField(
            model_name='departmentprofile',
            name='expected_salary_range',
        ),
        migrations.RemoveField(
            model_name='departmentprofile',
            name='imdb_profile',
        ),
        migrations.RemoveField(
            model_name='departmentprofile',
            name='key_skills',
        ),
        migrations.RemoveField(
            model_name='departmentprofile',
            name='linkedin_profile',
        ),
        migrations.RemoveField(
            model_name='departmentprofile',
            name='performed_work_location',
        ),
        migrations.RemoveField(
            model_name='departmentprofile',
            name='portfolio_link',
        ),
        migrations.RemoveField(
            model_name='departmentprofile',
            name='previous_projects',
        ),
        migrations.RemoveField(
            model_name='departmentprofile',
            name='resume_upload',
        ),
        migrations.RemoveField(
            model_name='departmentprofile',
            name='years_of_experience',
        ),
        migrations.AlterField(
            model_name='departmentprofile',
            name='approval_status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('inactive', 'Inactive')], db_index=True, default='pending', max_length=16),
        ),
    ]
