# Generated by ChatGPT on 2025-10-19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cineapp", "0009_remove_departmentprofile_additional_information_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="departmentprofile",
            name="additional_information",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="departmentprofile",
            name="awards_recognition",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="departmentprofile",
            name="certifications_training",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="departmentprofile",
            name="educational_qualification",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="departmentprofile",
            name="expected_salary_range",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="departmentprofile",
            name="imdb_profile",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="departmentprofile",
            name="key_skills",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="departmentprofile",
            name="linkedin_profile",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="departmentprofile",
            name="performed_work_location",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="departmentprofile",
            name="portfolio_link",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="departmentprofile",
            name="previous_projects",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="departmentprofile",
            name="resume_upload",
            field=models.FileField(blank=True, null=True, upload_to="uploads/"),
        ),
        migrations.AddField(
            model_name="departmentprofile",
            name="years_of_experience",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="departmentprofile",
            name="availability",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
