# Generated by Django 5.2.7 on 2025-10-19 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cineapp', '0010_departmentprofile_restore_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departmentprofile',
            name='approval_status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('inactive', 'Inactive'), ('draft', 'Draft')], db_index=True, default='pending', max_length=16),
        ),
    ]
